package com.fueldispatch.dispatch.domain;

import java.util.UUID;

/** Identity of a dispatch order. Generated by the domain, never by the database. */
public record OrderId(UUID value) {

    public OrderId {
        if (value == null) {
            throw new DomainValidationException("order id is required");
        }
    }

    public static OrderId newId() {
        return new OrderId(UUID.randomUUID());
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
